import './style.css';
import { TEST_IDS } from '../../eval/scenarios';
import catalog from '../../eval/catalog.json';
import { BrowserTestSession } from '../adapters/test-session';
import { FootballRenderer } from '../adapters/renderer';

document.getElementById('lab')!.innerHTML=`<main class="lab"><header><a href="./">← Volver al partido</a><h1>Laboratorio local</h1><p>69 escenarios reproducibles. Las comparaciones con PES requieren evidencia medida.</p></header><section class="lab-controls"><label>Caso<select id="case">${TEST_IDS.map(id=>`<option>${id}</option>`).join('')}</select></label><label>Semilla<input id="lab-seed" type="number" min="1" max="2147483647" value="2017"/></label><label>Variante<select id="variant"><option value="0">Control</option><option value="1">Intervención</option></select></label><button id="reset">Reiniciar caso</button><button id="step">1 tick</button><button id="sixty">60 ticks</button><button id="capture">Exportar evidencia</button></section><p id="description"></p><div id="lab-field"><canvas id="lab-radar" width="252" height="162"></canvas></div><output id="lab-status" aria-live="polite"></output><pre id="lab-events"></pre><p>El registro de envío al render no demuestra contacto visual ni mide latencia del dispositivo. Revisa los fotogramas y registra tus observaciones.</p></main>`;
const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id)as T;
let session=new BrowserTestSession(),renderer:FootballRenderer|null=null;
function draw(){renderer?.draw(session.previous,session.current,1,1/60);if(renderer)session.renderSubmitted(performance.now());const s=session.capture();el('lab-status').textContent=`Tick ${s.tick} · Hash ${s.worldHash} · ${s.state.phase} · ${renderer?'Render enviado':'Sin render 3D'}`;el('lab-events').textContent=JSON.stringify(s.state.events,null,2);}
function reset(){try{const id=el<HTMLSelectElement>('case').value,seed=Number(el<HTMLInputElement>('lab-seed').value),variant=Number(el<HTMLSelectElement>('variant').value)as 0|1;session.reset(id,seed,variant);renderer?.dispose();renderer=null;el('description').textContent=catalog.tests.find(t=>t.test_id===id)!.gameplay_property;try{renderer=new FootballRenderer(el('lab-field'),el<HTMLCanvasElement>('lab-radar'),session.state().config,[{shirt:'#f8edcf',shorts:'#273346',accent:'#e04b3f',pattern:'band'},{shirt:'#2352b3',shorts:'#142749',accent:'#53c2ef',pattern:'plain'}]);}catch(e){el('description').textContent+=` · WebGL: ${(e as Error).message}`;}draw();}catch(e){el('lab-status').textContent=(e as Error).message;}}
el('reset').onclick=reset;el('step').onclick=()=>{session.step();renderer?.advanceCamera(session.current);draw();};el('sixty').onclick=()=>{for(let i=0;i<60;i++){session.step();renderer?.advanceCamera(session.current);}draw();};
el('capture').onclick=()=>{const value=session.capture(),a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.href=url;a.download=`${value.testId}-${value.seed}-${value.tick}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
reset();
